name: CI

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff-format=udiff --dry-run --show-progress=dots --using-cache=no --verbose .

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extension-csv: curl, json, mbstring, simplexml, xdebug
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: |
          php --version
          ./vendor/bin/phpunit -c phpunit.xml
